/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_v1_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_api_v1_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/instruments/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Instrument */
        post: operations["confirm_instrument_api_v1_instruments_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Instruments */
        get: operations["search_instruments_api_v1_instruments_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Quotes */
        post: operations["refresh_quotes_api_v1_market_data_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/refresh/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Refresh Run */
        get: operations["get_refresh_run_api_v1_market_data_refresh__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Summary */
        get: operations["portfolio_summary_api_v1_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_api_v1_positions_get"];
        put?: never;
        /** Create Position */
        post: operations["create_position_api_v1_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Position */
        patch: operations["update_position_api_v1_positions__position_id__patch"];
        trace?: never;
    };
    "/api/v1/system/compatibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compatibility */
        get: operations["compatibility_api_v1_system_compatibility_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/compatibility/mcp-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe Mcp */
        post: operations["probe_mcp_api_v1_system_compatibility_mcp_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCreate */
        AccountCreate: {
            /** Cash Balance */
            cash_balance?: string | null;
            currency: components["schemas"]["Currency"];
            /** Name */
            name: string;
        };
        /** AccountPatch */
        AccountPatch: {
            /** Archived */
            archived?: boolean | null;
            /** Cash Balance */
            cash_balance?: string | null;
            /** Name */
            name?: string | null;
            /** Version */
            version: number;
        };
        /** AccountView */
        AccountView: {
            /** Archived At */
            archived_at: string | null;
            /** Cash Balance */
            cash_balance: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            currency: components["schemas"]["Currency"];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * AnalysisMode
         * @enum {string}
         */
        AnalysisMode: "full_mcp" | "bounded_context" | "disabled";
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: "equity" | "etf";
        /** CompatibilityReport */
        CompatibilityReport: {
            analysis_mode: components["schemas"]["AnalysisMode"];
            /** Contract Compatible */
            contract_compatible: boolean;
            /** Deep Analysis Enabled */
            deep_analysis_enabled: boolean;
            mcp_status: components["schemas"]["McpStatus"];
            /** Missing Capabilities */
            missing_capabilities?: string[];
            /** Reasons */
            reasons?: string[];
            state: components["schemas"]["CompatibilityState"];
            /**
             * Supported Versions
             * @default <0.2.0,>=0.1.11
             */
            supported_versions: string;
            /** Vibe Version */
            vibe_version?: string | null;
        };
        /**
         * CompatibilityState
         * @enum {string}
         */
        CompatibilityState: "compatible" | "degraded" | "unsupported";
        /**
         * Currency
         * @enum {string}
         */
        Currency: "CNY" | "HKD" | "USD";
        /** CursorPage[AccountView] */
        CursorPage_AccountView_: {
            /** Items */
            items: components["schemas"]["AccountView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CursorPage[PositionView] */
        CursorPage_PositionView_: {
            /** Items */
            items: components["schemas"]["PositionView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Fields */
            fields?: {
                [key: string]: unknown;
            } | null;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FailedProbe */
        FailedProbe: {
            /**
             * Reason
             * @default probe_execution_failed
             */
            reason: string;
            /** @default failed */
            status: components["schemas"]["McpStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstrumentConfirm */
        InstrumentConfirm: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
        };
        /** InstrumentSearchView */
        InstrumentSearchView: {
            asset_type: components["schemas"]["AssetType"];
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Canonical Symbol */
            canonical_symbol: string;
            currency: components["schemas"]["Currency"];
            market: components["schemas"]["Market"];
            /** Name */
            name: string;
            /** Sources */
            sources: string[];
        };
        /** InstrumentView */
        InstrumentView: {
            asset_type: components["schemas"]["AssetType"];
            /** Canonical Symbol */
            canonical_symbol: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            currency: components["schemas"]["Currency"];
            /** Id */
            id: string;
            market: components["schemas"]["Market"];
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * Market
         * @enum {string}
         */
        Market: "CN_SH" | "CN_SZ" | "CN_BJ" | "HK" | "US";
        /**
         * McpStatus
         * @enum {string}
         */
        McpStatus: "not_checked" | "available" | "missing" | "failed";
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Account Count */
            account_count: number;
            currency: components["schemas"]["Currency"];
            /** Estimated */
            estimated: boolean;
            /** Known Cash */
            known_cash: string;
            /** Market Value */
            market_value: string;
            /** Position Cost */
            position_cost: string;
            /** Position Count */
            position_count: number;
            /** Positions */
            positions: components["schemas"]["SummaryPosition"][];
            /** Stale Count */
            stale_count: number;
            /** Total Value */
            total_value: string;
            /** Unknown Cash Account Count */
            unknown_cash_account_count: number;
            /** Unrealized Pnl */
            unrealized_pnl: string;
            /** Unrealized Pnl Pct */
            unrealized_pnl_pct: string | null;
            /** Unvalued Cost */
            unvalued_cost: string;
            /** Unvalued Count */
            unvalued_count: number;
            /** Valued Count */
            valued_count: number;
            /** Valued Position Cost */
            valued_position_cost: string;
        };
        /** PositionCreate */
        PositionCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Average Cost */
            average_cost: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Note */
            note?: string | null;
            /** Quantity */
            quantity: string;
        };
        /** PositionPatch */
        PositionPatch: {
            /** Archived */
            archived?: boolean | null;
            /** Average Cost */
            average_cost?: string | null;
            /** Note */
            note?: string | null;
            /** Quantity */
            quantity?: string | null;
            /** Version */
            version: number;
        };
        /** PositionView */
        PositionView: {
            /** Account Id */
            account_id: string;
            /** Archived At */
            archived_at: string | null;
            /** Average Cost */
            average_cost: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Note */
            note: string | null;
            /** Quantity */
            quantity: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ProbeError */
        ProbeError: {
            /**
             * Code
             * @default MCP_PROBE_FAILED
             */
            code: string;
            /**
             * Message
             * @default Portfolio MCP compatibility probe failed
             */
            message: string;
        };
        /** ProbeFailureResponse */
        ProbeFailureResponse: {
            compatibility: components["schemas"]["CompatibilityReport"];
            error: components["schemas"]["ProbeError"];
            probe: components["schemas"]["FailedProbe"];
        };
        /**
         * QuoteState
         * @enum {string}
         */
        QuoteState: "fresh" | "stale" | "unavailable";
        /** RefreshItemView */
        RefreshItemView: {
            /** Error Code */
            error_code: string | null;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "updated" | "stale" | "unavailable";
            /** Provider */
            provider: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Instrument Ids */
            instrument_ids?: string[] | null;
        };
        /** RefreshRunView */
        RefreshRunView: {
            /** Finished At */
            finished_at: string | null;
            /** Items */
            items: components["schemas"]["RefreshItemView"][];
            /** Providers Used */
            providers_used: string[];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Stale */
            stale: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "partial" | "failed";
            /** Terminal Error */
            terminal_error: string | null;
            /** Unavailable */
            unavailable: number;
            /** Updated */
            updated: number;
        };
        /** SummaryPosition */
        SummaryPosition: {
            /** Account Id */
            account_id: string;
            /** Allocation */
            allocation: string | null;
            /** Average Cost */
            average_cost: string;
            /** Instrument Id */
            instrument_id: string;
            /** Market Value */
            market_value: string | null;
            /** Position Cost */
            position_cost: string;
            /** Position Id */
            position_id: string;
            /** Quantity */
            quantity: string;
            /** Quote As Of */
            quote_as_of: string | null;
            /** Quote Fetched At */
            quote_fetched_at: string | null;
            /** Quote Price */
            quote_price: string | null;
            /** Quote Provider */
            quote_provider: string | null;
            quote_state: components["schemas"]["QuoteState"];
            /** Unrealized Pnl */
            unrealized_pnl: string | null;
            /** Unrealized Pnl Pct */
            unrealized_pnl_pct: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_api_v1_accounts_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage_AccountView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_account_api_v1_accounts_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_v1_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_instrument_api_v1_instruments_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentView"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    search_instruments_api_v1_instruments_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentSearchView"][];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refresh_quotes_api_v1_market_data_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshRunView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_refresh_run_api_v1_market_data_refresh__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshRunView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_summary_api_v1_portfolio_summary_get: {
        parameters: {
            query: {
                currency: components["schemas"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_positions_get: {
        parameters: {
            query?: {
                archived?: boolean;
                account_id?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage_PositionView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_position_api_v1_positions_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_position_api_v1_positions__position_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compatibility_api_v1_system_compatibility_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityReport"];
                };
            };
        };
    };
    probe_mcp_api_v1_system_compatibility_mcp_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeFailureResponse"];
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
